In [26]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import requests
from sklearn.feature_extraction.text import CountVectorizer

# Text Processing

In [5]:
# url = 'https://www.kaggle.com/ishansoni/sms-spam-collection-dataset/data/spam.csv'
# requests.get(url)

In [121]:
df = pd.read_csv('spam.csv', encoding='latin-1')
df.tail()

v1                                                 v2 Unnamed: 2  \
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN

In [122]:
df.shape

(5572, 5)

In [123]:
df = df.drop(["Unnamed: 2","Unnamed: 3","Unnamed: 4" ], axis=1)

In [124]:
df['v2'][1]

'Ok lar... Joking wif u oni...'

In [125]:
df["v1"].value_counts()

ham     4825
spam     747
Name: v1, dtype: int64

In [213]:
sms_corpus = df['v2']
vec = CountVectorizer(min_df=2, stop_words='english', ngram_range=(1,2))
X = vec.fit_transform(sms_corpus)

In [214]:
X.shape

(5572, 9207)

In [215]:
X_arr = X.toarray()
X_arr.shape

(5572, 9207)

In [216]:
# max 단어
print('max cnt: ', X_arr.sum(axis=0).max(), 'max_index: ', X_arr.sum(axis=0).argmax())
print(vec.get_feature_names()[1454])

max cnt:  385 max_index:  8348
box385 m6


In [217]:
# max 10 개 단어
iidx = X_arr.sum(0).argsort()[-10:][::-1]
print(iidx)

[8348 4313 3604 4946 5797 3158 4948 4744 4440 3462]


In [218]:
[vec.get_feature_names()[i] for i in iidx]

['ur', 'just', 'gt', 'lt', 'ok', 'free', 'lt gt', 'll', 'know', 'good']

In [219]:
[X_arr.sum(0)[i] for i in iidx]

[385, 371, 318, 316, 292, 284, 276, 269, 261, 245]

In [220]:
# min
iidx2 = X_arr.sum(0).argsort()[:10]
print([vec.get_feature_names()[i] for i in iidx2])
print()
print([X_arr.sum(0)[i] for i in iidx2])

['leh busy', 'left mobile', 'left message', 'leaving qatar', 'leaving house', 'leaving congrats', 'leaves goodmorning', 'leaves good', 'leave pongal', 'wait finish']

[2, 2, 2, 2, 2, 2, 2, 2, 2, 2]


In [233]:
xx = ['aa','bb','cc']
xx_c ={}
yy = ['a','bb','s','cc','bb','f','cc']

for i in xx:
    xx_c[i] = 0

for i in yy:
    if i in xx:
        xx_c[i] = xx_c[i] + 1
        

In [234]:
xx_c

{'aa': 0, 'bb': 2, 'cc': 2}

In [229]:
[i for i in yy if i in xx]

['cc']

# 연습

In [35]:
corp = ['This is the first document.',
        'This document is the second document.',
        'And this is the third one.',
        'Is this the first document?']
corp

['This is the first document.',
 'This document is the second document.',
 'And this is the third one.',
 'Is this the first document?']

In [36]:
vect = CountVectorizer()
x = vect.fit_transform(corp)

In [37]:
x.toarray()

array([[0, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 2, 0, 1, 0, 1, 1, 0, 1],
       [1, 0, 0, 1, 1, 0, 1, 1, 1],
       [0, 1, 1, 1, 0, 0, 1, 0, 1]], dtype=int64)

In [38]:
vect.get_feature_names()

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']

In [182]:
aaa = np.array([0,1,2,3,4,5,6,7,8,9])
aaa

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [185]:
aaa[0], aaa[-1]

(0, 9)

In [187]:
aaa[:5]

array([0, 1, 2, 3, 4])

In [189]:
aaa[-5:]

array([5, 6, 7, 8, 9])

In [192]:
aaa[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [198]:
a3 = np.arange(12).reshape(3,2,2)

In [202]:
a3.sum(3)

AxisError: axis 3 is out of bounds for array of dimension 3