In [249]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.metrics import roc_curve,auc

In [39]:
df = pd.read_csv('breast_cancer.csv')
df.tail(5)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
564  926424         M        21.56         22.39          142.00     1479.0   
565  926682         M        20.13         28.25          131.20     1261.0   
566  926954         M        16.60         28.08          108.30      858.1   
567  927241         M        20.60         29.33          140.10     1265.0   
568   92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
564  ...        25.450          26.40           166.10      2027.0   
565  ...        23.690          38.25           155.00      1731.0   
566  ...        18.980          34.12           126.70      1124.0   
567  ...        25.740          39.42           184.60      1821.0   
568  ...         9.456          30.37            59.16       268.6   

     smoothness_worst  compactness_worst  concavity_worst  \
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
564                0.2216          0.2060                  0.07115  
565                0.1628          0.2572                  0.06637  
566                0.1418          0.2218                  0.07820  
567                0.2650          0.4087                  0.12400  
568                0.0000          0.2871                  0.07039  

[5 rows x 32 columns]

In [40]:
df['diagnosis'] = LabelEncoder().fit_transform(df['diagnosis'])

In [41]:
df.head()

id  diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302          1        17.99         10.38          122.80     1001.0   
1    842517          1        20.57         17.77          132.90     1326.0   
2  84300903          1        19.69         21.25          130.00     1203.0   
3  84348301          1        11.42         20.38           77.58      386.1   
4  84358402          1        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [42]:
# df.describe()
# df.info()

In [90]:
corrmat = df.corr()  # correlation matrix
corrmat.columns

Index(['diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [91]:
corrmat_sorted = corrmat.sort_values(by='diagnosis', ascending=False)
corrmat_sorted

diagnosis  radius_mean  texture_mean  perimeter_mean  \
diagnosis                 1.000000     0.730029      0.415185        0.742636   
concave points_worst      0.793566     0.744214      0.295316        0.771241   
perimeter_worst           0.782914     0.965137      0.358040        0.970387   
concave points_mean       0.776614     0.822529      0.293464        0.850977   
radius_worst              0.776454     0.969539      0.352573        0.969476   
perimeter_mean            0.742636     0.997855      0.329533        1.000000   
area_worst                0.733825     0.941082      0.343546        0.941550   
radius_mean               0.730029     1.000000      0.323782        0.997855   
area_mean                 0.708984     0.987357      0.321086        0.986507   
concavity_mean            0.696360     0.676764      0.302418        0.716136   
concavity_worst           0.659610     0.526911      0.301025        0.563879   
compactness_mean          0.596534     0.506124      0.236702        0.556936   
compactness_worst         0.590998     0.413463      0.277830        0.455774   
radius_se                 0.567134     0.679090      0.275869        0.691765   
perimeter_se              0.556141     0.674172      0.281673        0.693135   
area_se                   0.548236     0.735864      0.259845        0.744983   
texture_worst             0.456903     0.297008      0.912045        0.303038   
smoothness_worst          0.421465     0.119616      0.077503        0.150549   
symmetry_worst            0.416294     0.163953      0.105008        0.189115   
texture_mean              0.415185     0.323782      1.000000        0.329533   
concave points_se         0.408042     0.376169      0.163851        0.407217   
smoothness_mean           0.358560     0.170581     -0.023389        0.207278   
symmetry_mean             0.330499     0.147741      0.071401        0.183027   
fractal_dimension_worst   0.323872     0.007066      0.119205        0.051019   
compactness_se            0.292999     0.206000      0.191975        0.250744   
concavity_se              0.253730     0.194204      0.143293        0.228082   
fractal_dimension_se      0.077972    -0.042641      0.054458       -0.005523   
symmetry_se              -0.006522    -0.104321      0.009127       -0.081629   
texture_se               -0.008303    -0.097317      0.386358       -0.086761   
fractal_dimension_mean   -0.012838    -0.311631     -0.076437       -0.261477   
smoothness_se            -0.067016    -0.222600      0.006614       -0.202694   

                         area_mean  smoothness_mean  compactness_mean  \
diagnosis                 0.708984         0.358560          0.596534   
concave points_worst      0.722017         0.503053          0.815573   
perimeter_worst           0.959120         0.238853          0.590210   
concave points_mean       0.823269         0.553695          0.831135   
radius_worst              0.962746         0.213120          0.535315   
perimeter_mean            0.986507         0.207278          0.556936   
area_worst                0.959213         0.206718          0.509604   
radius_mean               0.987357         0.170581          0.506124   
area_mean                 1.000000         0.177028          0.498502   
concavity_mean            0.685983         0.521984          0.883121   
concavity_worst           0.512606         0.434926          0.816275   
compactness_mean          0.498502         0.659123          1.000000   
compactness_worst         0.390410         0.472468          0.865809   
radius_se                 0.732562         0.301467          0.497473   
perimeter_se              0.726628         0.296092          0.548905   
area_se                   0.800086         0.246552          0.455653   
texture_worst             0.287489         0.036072          0.248133   
smoothness_worst          0.123523         0.805324          0.565541   
symmetry_worst            0.143570         0.

In [92]:
cols = corrmat.nlargest(10, 'diagnosis')

In [93]:
y = df.values[:,0]
X = df.drop('diagnosis', axis=1).values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
clf = LogisticRegression()
clf.fit(X_train, y_train)
print(clf.score(X_test, y_test))

clf = SGDClassifier()
clf.fit(X_train, y_train)
print(clf.score(X_test, y_test))

In [96]:
clf.coef_, clf.intercept_

(array([[-1.18371617e+03, -6.22290687e+02, -6.26584932e+03,
         -1.71283827e+03, -6.60769597e+00,  2.30231483e+01,
          4.69815380e+01,  1.87799533e+01, -1.27561936e+01,
         -6.75440859e+00,  2.96610977e+00,  2.65687333e+00,
          1.46996538e+02,  3.23185936e+03,  1.90603481e-01,
          6.54343921e+00,  9.78339976e+00,  2.23823498e+00,
          6.21672596e-01,  3.27871998e-01, -1.25632004e+03,
         -3.67732817e+02, -5.76832042e+03,  2.70048278e+03,
         -6.02745839e+00,  7.78315335e+01,  1.18718563e+02,
          3.05814452e+01, -5.95137213e+00, -1.42514293e+00]]),
 array([-1309.5133509]))

In [97]:
df.columns

Index(['diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [139]:
# complete code

df = pd.read_csv('breast_cancer.csv')
df['diagnosis'] = LabelEncoder().fit_transform(df['diagnosis'])

y = df.values[:,1]
X = df.drop('diagnosis', axis=1).values
np.random.seed(42)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
clf = LogisticRegression()
clf.fit(X_train, y_train)
print(clf.score(X_test, y_test))

clf = SGDClassifier()
clf.fit(X_train, y_train)
print(clf.score(X_test, y_test))

0.6228070175438597
0.6228070175438597


In [243]:
# remove 'id' column
df = pd.read_csv('breast_cancer.csv')
df['diagnosis'] = LabelEncoder().fit_transform(df['diagnosis'])

df = df.drop('id', axis=1)
X, y = df.values[:,1:], df.values[:,0]
# np.random.seed(42)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.01)
clf = LogisticRegression()
clf.fit(X_train, y_train)
print(clf.score(X_test, y_test))
print(clf.predict(X_test))
clf.predict_proba(X_test)

# clf = SGDClassifier()
# clf.fit(X_train, y_train)
# print(clf.score(X_train, y_train))
# print(clf.predict(X_test))
# clf.predict_proba(X_test)

1.0
[0. 0. 0. 0. 0. 0.]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([[0.987542  , 0.012458  ],
       [0.95748056, 0.04251944],
       [0.96775652, 0.03224348],
       [0.98531423, 0.01468577],
       [0.99744964, 0.00255036],
       [0.97513723, 0.02486277]])

In [244]:
predict = clf.predict(X_test)
prob_score = clf.predict_proba(X_test)

In [245]:
predict

array([0., 0., 0., 0., 0., 0.])

In [246]:
prob_score

array([[0.987542  , 0.012458  ],
       [0.95748056, 0.04251944],
       [0.96775652, 0.03224348],
       [0.98531423, 0.01468577],
       [0.99744964, 0.00255036],
       [0.97513723, 0.02486277]])

In [247]:
prob_score[:,1]

array([0.012458  , 0.04251944, 0.03224348, 0.01468577, 0.00255036,
       0.02486277])

In [248]:
df = pd.DataFrame()
df['predict'] = predict
df['prob'] = prob_score[:,1]
df

predict      prob
0      0.0  0.012458
1      0.0  0.042519
2      0.0  0.032243
3      0.0  0.014686
4      0.0  0.002550
5      0.0  0.024863

In [255]:
# fpr = dict()
# tpr = dict()
# roc_curve = dict()
fpr, tpr, _ = roc_curve(y_test, df['prob'])  ###########
roc_auc = auc(fpr, tpr)

TypeError: 'dict' object is not callable